### PR TITLE
Zum-gali-gali-with-instruction final copy

### PR DESCRIPTION
**Pull request by barbra2020**

### CODE REVIEW

**Comment by michaelclapham** [comment]
First instruction should be
One: Play with the words _and_ sounds

**Comment by michaelclapham** [comment]
Very first zum is about a second too late coming in.

**Comment by michaelclapham** [comment]
At 0:17 Zum Gali Gali Zum
when it should be
Zum Gali Gali Gali Zum

**Comment by michaelclapham** [comment]
At about 0:20 person 2 is missing a Zum.

**Comment by michaelclapham** [comment]
At about 0:30 Dari Rum Dum Dum
I think should be
Dari Dum Dum Dum

**Comment by michaelclapham** [comment]
At 0:41 Zum Gali Gali Zum Gali Gali is missing a Gali
e.g should be
Zum Gali Gali _Gali_ Zum Gali Gali

**Comment by michaelclapham** [comment]
At about 0:54 Zum Gali Gali Zum
is missing a Gali

**Comment by michaelclapham** [comment]
At about 1:45
Three Add funny actions
should be
Three Add _fun_ actions

**Comment by brendawafula** [comment]
@barbra2020 you can edit your song by adding the missing words, like Gali  is repeated three times not twice.

**Comment by barbra2020** [comment]
@brendawafula  I have done the change  already

**Pull request merged**
