### PR TITLE
Feature/bella mama without instructions

### PR DESCRIPTION
**Pull request by brendawafula**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@brendawafula your song Bella mama looks good except for s few things. Its sang by two people and sometimes they overlap whilst singing. SO you should include the person column, so that these are displayed properly.

**Comment by brendawafula** [comment]
Am done with editing the comments on Bella mama song with instructions.

**Comment by maxwellfundi** [comment]
Alright, I will have a review

**Comment by maxwellfundi** [comment]
@michaelclapham  This looks good now :-)

**Pull request merged**
