### PR TITLE
Ay Gazoomba lyrics with instructions

### PR DESCRIPTION
**Pull request by estherwafula**

### CODE REVIEW

**Comment by michaelclapham** [comment]
At about 0:16 you're missing a Hey

**Comment by michaelclapham** [comment]
I'd love it if at 0:50 you added (faster) to the end, to indicate that the singing is better even faster!

**Comment by michaelclapham** [comment]
The final lyric could come in a second earlier.

**Comment by michaelclapham** [comment]
Sorry all of my comments so far have been for Ay Gazoomba without instructions.

**Comment by michaelclapham** [comment]
For Ay Gazoomba with instructions:
Quite a few times where you have Zum Gali Gali Zum you should have one more Gali.

**Comment by michaelclapham** [comment]
For the first few spoken lyrics, I'd like it if they don't show up as instructions, but as one of the blue or pink blobs singing.

**Comment by michaelclapham** [comment]
You have quite a few Eeeeh that should be Hey

**Comment by maxwellfundi** [comment]
@estherwafula lots of what at 0.13 the Zoomba Hey ought to come earlier
At 0.19 the people dont seem to alternate on the lyrics

The - Ay Gazoomba Zoomba Zoomba Ay Gazoomba Zoomba Eeeh at 1.13 should come earlier

**Comment by sylviawakoli** [comment]
@estherwafula  I have worked on your file and sending you a text file with the changes I made.

**Comment by sylviawakoli** [comment]
[AyGazoomba with Instruction.txt](https://github.com/michaelclapham/mhac-app-frontend/files/4609355/AyGazoomba.with.Instruction.txt)

@estherwafula  This is the file with the latest changes on your song.

**Comment by maxwellfundi** [comment]
Thank you @barbra2020  for helping out with getting this in shape. Cheers.

**Pull request merged**
